from enum import StrEnum


class JobStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    GENERATING_AUDIO = "GENERATING_AUDIO"
    RENDERING_SCENES = "RENDERING_SCENES"
    COMPOSING = "COMPOSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

